

services:
  # Traefik reverse proxy setup
  traefik:
    image: traefik:v2.9
    container_name: traefik-dashboard
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:8082  # Traefik entrypoint for HTTP requests
      - --entrypoints.websecure.address=:443  # HTTPS entrypoint (if needed)
    ports:
      - "8082:8082"  # Expose 8082 externally to map to Traefik’s web entry point
      - "8081:8081"  # Expose 8081 for the Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Traefik to listen to Docker events
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.services.api.loadbalancer.server.port=8081"  # Adjust for Traefik dashboard

  # Question Module Dashboard
  question_module_dashboard:
    build: 
      dockerfile: Dockerfile
    container_name: questions_module_dashboard
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qmms.rule=Host(`172.203.223.45`)"  # Host IP for accessing the service
      - "traefik.http.routers.qmms.entrypoints=web"  # Traefik web entry point (maps to :8082)
      - "traefik.http.services.qmms.loadbalancer.server.port=8081"  # Adjust to match exposed port in Dockerfile

networks:
  default:
    name: traefik-network
    driver: bridge
