services:
  vite-react-app:
    build: .
    ports:
      - "8080:8080"   #you can chnage it if you want to use another port
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

#Vite default port is 5173