
version: '3.8'

services:
  question-module-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: question_module_dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    env_file: ./env
    networks:
      - dev
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.question-module-dev.rule=Host(`testinterns.drishtee.in`)"   
       - "traefik.http.routers.question-module-dev.entrypoints=web"              
       - "traefik.http.services.question-module-dev.loadbalancer.server.port=8080" 

networks:
  dev:
    external: true
