version: '3.8'

services:
  # Traefik reverse proxy setup
  traefik:
    image: traefik:v2.9
    container_name: traefik-dashboard
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:8082
      - --entrypoints.websecure.address=:443
    ports:
      - "8082:8082"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8081"

  # Question Module Dashboard
  question_module_dashboard:
    build: 
      dockerfile: Dockerfile
    container_name: questions_module_dashboard
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qmms-dashboard.rule=Host(`172.203.223.45`)"
      - "traefik.http.routers.qmms-dashboard.entrypoints=web"
      - "traefik.http.services.qmms-dashboard.loadbalancer.server.port=8081"
