services:
  question_module_dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: questions_module_dashboard
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qmms-dashboard.rule=Host(`testinterns.drishtee.in`)"   
      - "traefik.http.routers.qmms-dashboard.entrypoints=web"              
      - "traefik.http.services.qmms-dashboard.loadbalancer.server.port=8080" 
    networks:
      - dev

networks:
  dev:
    external: true

